[package]
name = "identity-worker"
version = "0.0.0"
edition = "2024"

[dependencies]
identity-domain = { path = "../../../crates/identity-domain" }
identity-application = { path = "../../../crates/identity-application" }
identity-cloudflare = { path = "../../../crates/identity-cloudflare" }
worker = { version = "0.8.7", features = ["d1"] }
