//! Application registration: the OAuth client lifecycle.
//!
//! Registering an application is an *administrative* act, so every command
//! here takes an actor. That is the difference from [`crate::accounts`], where
//! no command names an actor, and the difference is deliberate: an application
//! whose redirect URIs you can change is an application you can steal a code
//! with.

use identity_domain::application::ApplicationId;
use identity_domain::user::UserId;
use serde::{Deserialize, Serialize};

use crate::error::ApplicationResult;

/// An application, as the admin surface sees it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ApplicationView {
    /// The application's identifier.
    pub application_id: ApplicationId,
    /// The public `client_id`.
    pub client_id: String,
    /// The display name.
    pub display_name: String,
    /// Whether it may be used.
    pub status: identity_domain::application::ApplicationStatus,
    /// Which access mode it registered under.
    pub access_mode: identity_domain::application::ApplicationAccessMode,
    /// Its registered redirect URIs.
    pub redirect_uris: Vec<String>,
    /// Its registered scopes.
    pub allowed_scopes: Vec<String>,
    /// When its secret was last rotated, as milliseconds since the Unix epoch.
    /// `None` means "never", which for a confidential client is a finding.
    pub secret_rotated_at_ms: Option<i64>,
}

/// Register a new application.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RegisterApplication {
    /// The administrator registering it.
    pub actor_id: UserId,
    /// The public `client_id`. Generated by the server when absent.
    pub client_id: Option<String>,
    /// The display name.
    pub display_name: String,
    /// Which access mode.
    pub access_mode: identity_domain::application::ApplicationAccessMode,
    /// The redirect URIs to register. Each must be absolute and
    /// fragment-free; the domain model refuses the rest.
    pub redirect_uris: Vec<String>,
    /// The scopes to register.
    pub allowed_scopes: Vec<String>,
    /// Register a confidential client, one that will present a secret.
    pub confidential: bool,
}

/// The result of registering an application.
#[derive(Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RegisterApplicationOutcome {
    /// The registered application.
    pub application: ApplicationView,
    /// The client secret, shown **once**.
    ///
    /// `Option` because a public client has none. It is never persisted in
    /// cleartext and never appears in any later read: the only way to obtain
    /// it again is [`RotateClientSecret`]. A field named `client_secret` in a
    /// `Debug` derive is a log-leak risk, which is why this type carries
    /// `#[derive(Clone, PartialEq, Eq, Serialize)]` and no `Debug`.
    pub client_secret: Option<ClientSecret>,
}

impl core::fmt::Debug for RegisterApplicationOutcome {
    /// The secret is withheld, not merely omitted. Deriving `Debug` on this
    /// struct would be a compile error rather than a silent leak, which is the
    /// whole point of `ClientSecret` having no `Debug`; the impl below is the
    /// one place a secret is allowed to reach a `Debug` formatter, and it puts
    /// a placeholder there. Deleting it breaks every call site that formats the
    /// outcome — including the ones nobody remembers adding.
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("RegisterApplicationOutcome")
            .field("application", &self.application)
            .field(
                "client_secret",
                &self.client_secret.as_ref().map(|_| "<redacted>"),
            )
            .finish()
    }
}

/// A client secret. Opaque, and deliberately without `Debug`.
///
/// Wrapping it in a newtype rather than a `String` is what lets a future
/// `zeroize` on drop, and — more immediately — it makes `{:?}` a compile error
/// for anyone who tries to log one.
#[derive(Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(transparent)]
pub struct ClientSecret(String);

impl ClientSecret {
    /// Mint a secret. Called by the implementation, not by a caller.
    ///
    /// # Errors
    ///
    /// [`crate::error::ApplicationError::Domain`] when the value is not
    /// 256 bits of base64url or longer.
    pub fn new(value: impl Into<String>) -> crate::error::ApplicationResult<Self> {
        let value = value.into();
        identity_domain::error::require_non_blank("client_secret", &value)?;
        // 43 base64url characters is 256 bits. Anything shorter is not a
        // secret.
        if value.len() < 43 {
            return Err(identity_domain::error::DomainError::invalid(
                "client_secret",
                "must be at least 43 base64url characters",
            )
            .into());
        }
        Ok(Self(value))
    }

    /// Borrow the secret for hashing, before storage.
    ///
    /// The only legitimate caller is the hash step in the repository. Exposing
    /// it as `&str` rather than `impl AsRef<str>` is a small friction toward
    /// remembering that.
    ///
    /// # Errors
    ///
    /// None.
    #[must_use]
    pub fn expose_for_hashing(&self) -> &str {
        &self.0
    }
}

/// Register an application.
pub trait RegisterApplicationCommand {
    /// # Errors
    ///
    /// [`crate::error::ApplicationError::Forbidden`] when `actor_id` is not an
    /// administrator; [`crate::error::ApplicationError::Domain`] for a
    /// duplicate `client_id` or a bad redirect URI.
    fn register_application(
        &self,
        input: RegisterApplication,
    ) -> ApplicationResult<RegisterApplicationOutcome>;
}

/// Change a registered application's metadata.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct UpdateApplication {
    /// The administrator making the change.
    pub actor_id: UserId,
    /// The application being changed.
    pub application_id: ApplicationId,
    /// A new display name, if changing it.
    pub display_name: Option<String>,
    /// Redirect URIs to add. Additive only: a URI is never removed by an
    /// update, because a removed URI takes live clients down instantly and
    /// silently. Removal is a separate, deliberate operation.
    pub add_redirect_uris: Vec<String>,
    /// Scopes to add.
    pub add_scopes: Vec<String>,
    /// A new status, if changing it.
    pub status: Option<identity_domain::application::ApplicationStatus>,
}

/// Change an application's metadata.
pub trait UpdateApplicationCommand {
    /// # Errors
    ///
    /// [`crate::error::ApplicationError::Forbidden`] for a non-administrator,
    /// [`crate::error::ApplicationError::Domain`] for an invalid URI.
    fn update_application(
        &self,
        input: UpdateApplication,
    ) -> ApplicationResult<ApplicationView>;
}

/// Rotate a confidential client's secret.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RotateClientSecret {
    /// The administrator rotating it.
    pub actor_id: UserId,
    /// The application whose secret rotates.
    pub application_id: ApplicationId,
    /// Keep the previous secret valid for a grace period, as milliseconds
    /// since the Unix epoch. `Some(0)` means "invalid immediately". Rotation
    /// with a grace period is the difference between a rotation and an outage.
    pub grace_period_ms: Option<i64>,
}

/// The result of a secret rotation.
#[derive(Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RotateClientSecretOutcome {
    /// The new secret, shown once.
    pub client_secret: ClientSecret,
    /// When the old secret stops being accepted, as milliseconds since the
    /// Unix epoch.
    pub previous_secret_valid_until_ms: i64,
}

/// Rotate a client secret.
pub trait RotateClientCommand {
    /// # Errors
    ///
    /// [`crate::error::ApplicationError::Domain`] when the application is a
    /// public client and has no secret to rotate.
    fn rotate_client_secret(
        &self,
        input: RotateClientSecret,
    ) -> ApplicationResult<RotateClientSecretOutcome>;
}

/// Grant an application access to a user's account.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GrantApplicationAccess {
    /// The user granting it.
    pub user_id: UserId,
    /// The application being granted.
    pub application_id: ApplicationId,
    /// The scopes being granted. Narrowed to the application's registration.
    pub scopes: Vec<String>,
}

/// The scopes actually granted.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GrantApplicationAccessOutcome {
    /// The intersection of what was asked for and what is registered.
    pub granted_scopes: Vec<String>,
}

/// Grant an application access to the caller's account.
pub trait GrantApplicationAccessCommand {
    /// # Errors
    ///
    /// [`crate::error::ApplicationError::Forbidden`] when the session is not
    /// at AAL2. A grant is a standing authorization; requiring a step-up is
    /// what stops a walk-up attacker from granting an application and coming
    /// back tomorrow.
    fn grant_application_access(
        &self,
        input: GrantApplicationAccess,
    ) -> ApplicationResult<GrantApplicationAccessOutcome>;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_client_secret_cannot_be_printed() {
        // The newtype has no `Debug`, so `{:?}` does not compile. This test
        // cannot assert the absence of a trait impl, but it can assert the
        // serialised form, and the *absence of a Debug derive* is enforced by
        // the type not having one — recorded here so a future `#[derive(Debug)]`
        // is a deliberate diff against a documented reason.
        let s = ClientSecret::new("a".repeat(43)).expect("valid");
        let json = serde_json::to_string(&s).expect("serializable");
        assert_eq!(json.len(), 45, "a 43-char secret serialises quoted");
    }

    #[test]
    fn a_short_secret_is_refused() {
        // A 43-character minimum is 256 bits of base64url. Anything less is
        // not a secret, and accepting one would store a guessable credential.
        assert!(ClientSecret::new("short").is_err());
        assert!(ClientSecret::new("a".repeat(42)).is_err());
        assert!(ClientSecret::new("a".repeat(43)).is_ok());
    }

    #[test]
    fn a_rotation_outcome_carries_the_old_expiry() {
        // Without this, "rotate with a grace period" is indistinguishable
        // from "rotate and cut everyone off at once", which is an outage.
        let outcome = RotateClientSecretOutcome {
            client_secret: ClientSecret::new("a".repeat(43)).expect("valid"),
            previous_secret_valid_until_ms: 1_700_000_000_000,
        };
        let json = serde_json::to_string(&outcome).expect("serializable");
        assert!(json.contains("previous_secret_valid_until_ms"), "{json}");
    }

    #[test]
    fn every_application_command_names_its_actor() {
        // The boundary between the administrative application surface and the
        // self-service one. A command that mutates a registration and does not
        // name an actor has no way to be authorized.
        let inputs: Vec<serde_json::Value> = vec![
            serde_json::to_value(RegisterApplication {
                actor_id: UserId::new().expect("uuid"),
                client_id: None,
                display_name: "x".into(),
                access_mode: identity_domain::application::ApplicationAccessMode::Oidc,
                redirect_uris: vec![],
                allowed_scopes: vec![],
                confidential: true,
            })
            .expect("serializable"),
            serde_json::to_value(RotateClientSecret {
                actor_id: UserId::new().expect("uuid"),
                application_id: ApplicationId::new().expect("uuid"),
                grace_period_ms: Some(0),
            })
            .expect("serializable"),
        ];
        for input in inputs {
            assert!(
                input.get("actor_id").is_some(),
                "an application-registration command must name its actor"
            );
        }
    }
}
